#!/bin/bash

# ./runStats pprAI scenarioRecordings scenarioFrames testCases 2
# ./runStats footstepAI scenarioRecordings scenarioFrames testCases 3
# ./runStats ccAI scenarioRecordings scenarioFrames testCases 10
# Or
# ./runStats ccAI scenarioRecordings scenarioFrames testCases 10 data/2
# ./runStats ccAI scenarioRecordings scenarioFrames testCases 2000 data/1/ 24381

# the root directory from here where everything will be stored

if [ -z "$6" ]
  then
   dataPath="data"
  else
   dataPath="$6"
fi


benchmarkTechnique="composite02"
aiModuleName=$1
recordingDirectory="$dataPath/$2/"
frameDirectory="$dataPath/$3/"
ailogFilePath="$dataPath/$aiModuleName.log"
testCasePath="$dataPath/$4/"
scenarioSetAI="pprAI" # choose the set of scenarios to re-run
# the initial id for the used scenarioSetAI
if [ -z "$7" ]
  then
   scenarioSetInitID="0"
  else
   scenarioSetInitID="$7"
fi
scenarioSetPath="data/scenarios/$scenarioSetAI/"
numScenarios=$5
frameSize="640x480"

# configFile="configs/ppr-config.xml"
configFile="configs/$aiModuleName-config.xml"

# clear folders containing data
# ./clearOldStatFiles $recordingDirectory $frameDirectory $testCasePath $ailogFilePath


moduleParams="scenario,scenarioAI=$aiModuleName,numScenarios=$numScenarios,useBenchmark,benchmarkTechnique=$benchmarkTechnique,benchmarkLog=$dataPath/test.log,checkAgentValid,reducedGoals,fixedSpeed,fixedDirection,checkAgentRelevant,minAgents=3,ailogFileName=$ailogFilePath" #,randomSeed=120"
moduleParams="$moduleParams,recFile=rec,recFileFolder=$recordingDirectory" # save record files for later benchmarking
# moduleParams="$moduleParams,dumpFrames,framePath=$frameDirectory" #save test frames to make videos

# Only one of the following line should ever be included. THe operations exclude eachother.
moduleParams="$moduleParams,dumpTestCases,testCasePath=$testCasePath" # part for dumping testcases
# moduleParams="$moduleParams,scenarioSetPath=$scenarioSetPath,scenarioSetInitId=$scenarioSetInitID" # can be used to load bunch of testcases

# moduleParams="$moduleParams -commandline" 

# ../build/bin/steersim -module $moduleParams -config $configFile
# valgrind ../build/bin/steersim -module $moduleParams -config $configFile


# encode all of the videos
# echo "tools/encodeVideos $frameDirectory $numScenarios $frameSize"
# tools/encodeVideos "$frameDirectory" $numScenarios $frameSize

#insert everything into database
python InsertStatistics.py $moduleParams $configFile
